name: sample workflow

on: push
jobs:
     first_job:
              runs_on: windows_latest
              steps:
      
              name: checkout repository      //need to checkout repo
              uses: actions/checkout@v4      //using action marketplace

              name: list files
              run: ls

              name: read files
              run: cat hello.txt

