name: sample workflow

on: push
jobs:
     first_job:
              runs_on: windows_latest
              steps:
      
              name: checkout repository
              uses: actions/checkout@v4

              name: list files
              run: ls

              name: read files
              run: cat hello.txt

